Add fileStorageUploadField and fileUploadField Components to UI Samples
jmix-framework/jmix-ui-samples-2 pull request #16
Opened 2023-12-08 10:23 UTC by AmirShelli

This pull request introduces two new components to the UI samples: `fileStorageUploadField` and `fileUploadField`.
Added their description and its Russian localization.

2023-12-11 08:53 UTC, honest-niceman commented on src/main/java/io/jmix/uisamples/entity/Document.java
> +@JmixEntity
Please look other entities declaration. @Entity and @Table annotations are missing here

2023-12-11 09:05 UTC, honest-niceman commented on src/main/java/io/jmix/uisamples/view/flowui/components/fileupload/filestorageuploadfield/FileStorageUploadFieldSample.java
> +    @ViewComponent
Do not mix @Autowired and @ViewComponent fields. Please define all autowired field first, then all @ViewComponent

2023-12-11 09:07 UTC, honest-niceman commented on src/main/java/io/jmix/uisamples/view/flowui/components/fileupload/filestorageuploadfield/FileStorageUploadFieldSample.java
> +        if (receiver instanceof FileTemporaryStorageBuffer) {
Use smart instanceof construction from java17. E.g:

if (receiver instanceof FileTemporaryStorageBuffer storageBuffer) {

2023-12-11 09:18 UTC, honest-niceman commented on src/main/java/io/jmix/uisamples/view/flowui/components/fileupload/filestorageuploadfield/FileStorageUploadFieldSample.java
> +    @Autowired
Add empty line before first field

2023-12-11 09:19 UTC, honest-niceman commented on src/main/resources/io/jmix/uisamples/view/flowui/components/avatar/avatar-en.html
> +<p>An avatar can contain a name, an abbreviation, an icon. By default, the abbreviation is the first characters of the name.</p>
Basically, this change has nothing related to this PR. Isn't it?

2023-12-11 09:22 UTC, honest-niceman commented on src/main/resources/io/jmix/uisamples/menu/uisamples-menu.xml
> +        <menu id="upload-field">
The component should be added in alphabetic order, not as the second item

2023-12-11 09:23 UTC, honest-niceman commented on src/main/resources/io/jmix/uisamples/menu/uisamples-menu.xml
> +                    <file name="io/jmix/uisamples/entity/Picture.java"/>
Check out the documentation link. It leads to the 404 page

2023-12-11 09:24 UTC, honest-niceman commented on src/main/java/io/jmix/uisamples/view/flowui/components/fileupload/fileuploadfield/FileUploadFieldSample.java
> +}
Keep looking at file ends. Only one empty line at the end. Not two or zero empty lines.

2023-12-11 09:25 UTC, honest-niceman commented on src/main/java/io/jmix/uisamples/view/flowui/components/fileupload/filestorageuploadfield/FileStorageUploadFieldSample.java
> +            final FileUploadSucceededEvent<FileStorageUploadField> event) {
Do we have a linter for exceeded line length? If not, i think it's better to not split method declaration into two lines

2023-12-11 09:26 UTC, honest-niceman commented on src/main/resources/io/jmix/uisamples/messages_en.properties
> +uisamples-menu-config.upload-field = UploadField
I think it's better to name it "Managing files"

2023-12-11 09:27 UTC, honest-niceman requested changes
Please check out ny suggestions

2023-12-11 12:03 UTC, AmirShelli commented
Implemented the requested changes.

2023-12-11 12:44 UTC, honest-niceman approved these changes
Looks good to me

2023-12-12 11:25 UTC, honest-niceman commented
@knstvk please take a look, LGTM

2023-12-13 13:18 UTC, knstvk commented
@AmirShelli - please explain in the description:
- how to use the example: what file types and sizes are accepted.
- the fact that the example of fileStorageUploadField does not actually saves the file in the storage. Add a comment to the code explaining that it's just a demo code and should not be used in production.

Also, how the drop zone is supposed to work? When I drag-drop a file to the component from macOS Finder, the file is downloaded instead of uploaded.

2023-12-14 08:57 UTC, AmirShelli commented
@knstvk 
Implemented the requested changes:
* Adjusted the description accordingly
* Included instructions on how to use the drag-and-drop zone
* Changed the section name to "File Upload Fields"

2023-12-14 14:03 UTC, merged