Add new sample - VirtualList inline editor
jmix-framework/jmix-ui-samples-2 pull request #29
Opened 2024-03-15 15:26 UTC by KartnDev

2024-03-18 07:20 UTC, KremnevDmitry requested changes

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/entity/food/FoodDetailView.java
> +    public void onFoodIconUploadFileUploadSucceeded(final FileUploadSucceededEvent<FileUploadField> event) {
Date binding has left the chat...


Replace with: 
```xml
<fileUploadField id="foodIconUpload" dataContainer="foodDc" property="icon" uploadIcon="UPLOAD" uploadText=""/>
```

After that....
`ItemPropertyChangeEvent` would be much better:
```java
    @Subscribe(id = "foodDc", target = Target.DATA_CONTAINER)
    protected void onPropertyChangeListener(InstanceContainer.ItemPropertyChangeEvent<Food> event) {
        if ("icon".equals(event.getProperty())) {
            initIconFields();
        }
    }
```

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/entity/food/FoodDetailView.java
> +                foodIcon.setImageResource(new StreamResource(iconFileName, () -> new ByteArrayInputStream(getEditedEntity().getIcon())));
Exceeds the 120 character limit

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +            infoLayout.setMargin(false);
Margin is `false` by default, why are these lines (3 times)?

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +            rootCardLayout.setSpacing(true);
Spacing is `true` by default??
![image](https://github.com/jmix-framework/jmix-ui-samples-2/assets/75516667/ceab5e55-9742-4dc5-84be-acc782caa08c)

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +        return new ComponentRenderer<>(item -> {
Spaghetti is not the best way to organize code...
In the description of the sample, you described three renderer elements: `Avatar`, `InfoLayout` and `ButtonsLayout`.
Why not decompose the code and move the generation code of these three elements into separate methods??

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +                        FoodDetailView detail = closeEvent.getSource().getView();
This variable is not used anywhere except in the `if` block. Why is it declared outside?

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +                    .build()
Why??

![image](https://github.com/jmix-framework/jmix-ui-samples-2/assets/75516667/01ba1c81-1ab0-4056-9c4d-6aa8c9fcc586)

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +        List<Food> foodList = new ArrayList<Food>();
![image](https://github.com/jmix-framework/jmix-ui-samples-2/assets/75516667/c3f43e52-2d47-4db0-8f60-3d305a376e99)

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +                2, "META-INF/resources/icons/components/virtuallist-food/sandwich.png"));
`META-INF/resources/icons/components` has already been used several times, maybe move it to a separate static variable? `ICONS_PATH_ROOT`?

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +                    FoodDetailView detail = closeEvent.getSource().getView();
The same

2024-03-18 07:20 UTC, KremnevDmitry commented on src/main/java/io/jmix/uisamples/view/flowui/components/virtuallist/inlineeditor/VirtualListInlineEditor.java
> +                .build()
The same

2024-03-25 11:30 UTC, KartnDev commented on src/main/resources/io/jmix/uisamples/messages_en.properties
> -
I deleted this message coz i didn't found any key usage... We can undo this deletion just for commit history purity, but i think in other way we need to delete it (I'm pretty sure this line is not used anywhere)
<img width="744" alt="image" src="https://github.com/jmix-framework/jmix-ui-samples-2/assets/43281522/7899f8c6-b93b-4440-ad44-ce031a75dcbd">

2024-03-25 14:53 UTC, merged